### ISSUE TITLE
CPS tests fail for parallel with failFast: true

### ISSUE THREAD

**Issue by seanf** [lesfurets/JenkinsPipelineUnit#17]
When using BasePipelineTestCPS with `parallel` and a task Map which includes `failFast: true`, I get this exception:

```
com.cloudbees.groovy.cps.impl.CpsCallableInvocation
	at sun.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at Jenkinsfile.run(Jenkinsfile)
	at TestJenkinsfile.should_execute_without_errors(TestJenkinsfile.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I assume it's because of CPS, but nothing in there really explains the exception. However, if I use `printCallStack()` the call stack shows this:
> `Jenkinsfile.echo(ERROR integrationTests: groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.cps.PipelineTestHelperCPS$_closure1$_closure4.doCall() is applicable for argument types: (java.lang.String, java.lang.Boolean) values: [failFast, true]
Possible solutions: doCall(java.lang.String, groovy.lang.Closure), findAll(), findAll())`

This is the only documentation I can currently find for failFast: https://github.com/jenkinsci/pipeline-plugin/pull/88

I think this _may_ be legal syntax too: `parallel tasksMap, failFast: true`
but it fails with this call stack:
> `Jenkinsfile.echo(ERROR integrationTests: groovy.lang.MissingMethodException: No signature of method: Jenkinsfile.parallel() is applicable for argument types: (java.util.LinkedHashMap, java.util.LinkedHashMap) values: [[failFast:true], [JBOSSEAP:com.cloudbees.groovy.cps.impl.CpsClosure@3b08f438]])`

**Comment by ozangunalp** [comment]
This must have something to do with the default mock of `parallel` step, which does not consider the `failFast: true` syntax. Thanks for the pointer I'll look into it.
