### ISSUE TITLE
SharedLib functions with more than one parameter not supported

### ISSUE THREAD

**Issue by kpdroiddev** [lesfurets/JenkinsPipelineUnit#21]
Hello,
I currently try to test my shared library with JenkinsPipelineUnit. I always get the error message

> groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.PipelineTestHelper$_setGlobalVars_closure9$_closure18$_closure19.call() is applicable for argument types: (java.lang.String, java.lang.String) values: [Some, String]

To avoid issues in my code I took from your commons library the sayHello.groovy and add it to my SharedLib. It is working if the call is like original:
```groovy
//In Jenkinsfile:
sayHello('Some')

// in sayHello.groovy:
def call(String name = 'human') {
```

but if I change sayHello to have two parameters I get the mentioned error:
```groovy
//In Jenkinsfile:
sayHello('Some', 'String')

// in sayHello.groovy:
def call(String name = 'human', String secondname = 'some') {
```

first lines of stacktrace:
```
MethodSignature{ name='sayHello', args=[class java.lang.String, class java.lang.String] }=com.lesfurets.jenkins.unit.PipelineTestHelper$_setGlobalVars_closure9$_closure18$_closure19@6caf0677
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.PipelineTestHelper$_setGlobalVars_closure9$_closure18$_closure19.call() is applicable for argument types: (java.lang.String, java.lang.String) values: [Some, String]
Possible solutions: any(), any(), find(), collect(), grep(), dump()

java.lang.NullPointerException: Cannot get property 'Stage' on null object

	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:257)
	at org.codehaus.groovy.runtime.dgm$241.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
```

Then I also changed my actual function of my shared lib to have only one parameter (hardcoded the others) and suddenly my unit test is running smooth.

Can you please check what could cause this? Thank you!

Cheers

**Comment by ozangunalp** [comment]
Hi @kpdroiddev,

At first glace it seems like an issue with searching methods with parameter default values. I'll take a look as soon as I can. Meanwhile can you remove default values from your call method definition and see what it gives ? 

Thanks,

**Comment by kpdroiddev** [comment]
Hello,
still the same.

```groovy
//In sayHello.groovy
def call(String name, String secondname) {
```

```
MethodSignature{ name='sayHello', args=[class java.lang.String, class java.lang.String] }=com.lesfurets.jenkins.unit.PipelineTestHelper$_setGlobalVars_closure9$_closure18$_closure19@6caf0677
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.PipelineTestHelper$_setGlobalVars_closure9$_closure18$_closure19.call() is applicable for argument types: (java.lang.String, java.lang.String) values: [Some, String]
Possible solutions: any(), any(), find(), collect(), grep(), dump()

java.lang.NullPointerException: Cannot get property 'Stage' on null object

	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:257)
	at org.codehaus.groovy.runtime.dgm$241.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at Jenkinsfile_testReportError$_run_closure1.doCall(Jenkinsfile_testReportError:45)
```

**Comment by EQuincerot** [comment]
Hello @kpdroiddev 

Thanks for your response. However I cannot reproduce the issue you mention.
Could you maybe create a test in this project to reproduce the issue or send us an example in a private message?

I see you have a NullPointerException as well, occuring in Jenkinsfile_testReportError:45
It seems you get 'Stage' on a null object. Did you mock the object containing the stage correctly?

Thanks for your feedback.

**Comment by kpdroiddev** [comment]
Hello @EQuincerot ,

I don't know where the NullPointer comes from as if I try with only one parameter the test passes.
But to be sure I created a new test case based on your files, in your project and tried it, still the same. I will attach the files.

Cheers and thanks for the support!
[Reproduce_Bug21.zip](https://github.com/lesfurets/JenkinsPipelineUnit/files/934873/Reproduce_Bug21.zip)

**Comment by EQuincerot** [comment]
Thanks for the example, it's helpful!
We'll investigate and try to find a fix.

**Comment by kpdroiddev** [comment]
Hello @EQuincerot ,

I tried your Branch "Remove branch encapsulation" and it works smooth for me, thank you for the quick fix!
Cheers

**Comment by EQuincerot** [comment]
Thanks for the quick feedback @kpdroiddev !

**Comment by fl-max** [comment]
For anyone stumbling up this; this appears to only work when you have default values set in your `def call(...)` method.
