### ISSUE TITLE
How to integrate JenkinsPipelineUnit within IntelliJ

### ISSUE THREAD

**Issue by flyingclamking** [lesfurets/JenkinsPipelineUnit#65]
Greeting,

I am trying to add JenkinsPipelineUnit into my project. I am having trouble with some setups.

Here is part of build.gradle:
```
sourceSets {
    main {
        groovy {
            srcDirs = ['vars', 'src']
        }
    }
    test {
        groovy {
            srcDirs = ['test/groovy']
        }
    }
}
```

As you can see, srcDirs for main are vars and src. I did this because I want IntelliJ to be aware of all the source code so it can do magic stuff(like jump into the source code) for me.

However, when I try to run tests, I get an error:
```
java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

This error will go away if I change main srcDirs to only 'src'. My guess is if I include 'vars' in source dir, somehow the test framework will not treat them as global libs instead of normal classes.

But if I remove that, IntelliJ cannot recognize all files in vars so the code reference functionality will stop working.

I am wondering have anybody seen this kind of problem before? maybe in another IDE?

Thanks

**Comment by flyingclamking** [comment]
I fix this by adding the following code:
```
gradle.addListener(new TaskExecutionListener() {

    @Override
    void beforeExecute(Task task) {
        if (task.name.equals("compileGroovy")) {
            tasks.prepareUnitTest.execute()
        }
    }

    @Override
    void afterExecute(Task task, TaskState taskState) {
        if (task.name.equals("test")) {
            sourceSets {
                main {
                    groovy {
                        srcDirs = ['vars', 'src']
                    }
                }
            }
        }
    }
})
```
