### ISSUE TITLE
Include some dead simple example for a Maven project

### ISSUE THREAD

**Issue by batmat** [lesfurets/JenkinsPipelineUnit#9]
Hello,

I'm trying to play with your tool, which seems very neat :-). But I immediately hit a wall, I'm using a `pom.xml` and created a simple JUnit, but for some reason I get an NPE on the `gse` variable from https://github.com/lesfurets/JenkinsPipelineUnit/blob/660d8dc51266e50f2aa741ce9fe173342737333e/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L53

Just trying to simply load an existing script

```java
public class AstroTest extends BasePipelineTest {
    @Test
    public void bim() throws Exception {
        loadScript("Jenkinsfile"); // fails with NPE
        System.out.println("WAT");
    }
}
```

But get the following stack trace:

```
	at com.lesfurets.jenkins.unit.PipelineTestHelper.loadScript(PipelineTestHelper.groovy:204)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$loadScript$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.lesfurets.jenkins.unit.BasePipelineTest.loadScript(BasePipelineTest.groovy:83)
	at com.cloudbees.astro.AstroTest.bim(AstroTest.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I guess it's something like it does not find the script, but I've no clue about where to put it or so. It would be great if the gse nullity would be checked to provide possibly more guidance (failing on https://github.com/lesfurets/JenkinsPipelineUnit/blob/660d8dc51266e50f2aa741ce9fe173342737333e/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L204 because `gse` is null in this case)

I'm trying other combinations in the meantime.

Thanks!

**Comment by batmat** [comment]
OK, got it reading the code, setUp() *must* be implemented* to get it working. I still think the NPE is unexpected though: would be better to throw an `IllegalStateException` or so telling the user like: "GroovyScriptEngine is uninitialized, you probably want to override setup. see the doc http://bla".

Will try to see if I can contribute it once I'm past the basics. Thanks!

**Comment by ozangunalp** [comment]
Hi Baptiste, 

Great to see that you are taking the tool for a spin.

Yes the setUp must be called to initialize/configure the script engine. 
The class BasePipelineTest doesn't do that to be compatible with different testing frameworks like junit, testng, spock etc.

You are absolutely right about the NPE. I'm working to improve on configuration issues. 
The tool still needs polishing so don't hesitate fiddle around!

**Comment by icereed** [comment]
Here is an example project:
https://github.com/macg33zr/pipelineUnit
